# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install bash, curl, tar, xz for bun install
RUN apk add --no-cache bash curl tar xz \
    && curl -fsSL https://bun.sh/install | bash \
    && mv /root/.bun/bin/bun /usr/local/bin/bun

# Set working directory
WORKDIR /app

# Copy dependency specs
COPY package.json package-lock.json ./

# Install dependencies using Bun
RUN bun install --production

# Copy source code
COPY . .

# Default command
CMD ["bun", "run", "src/index.ts"]
